#!/usr/bin/env python
# coding: utf-8

"""USAGE: rpmutil.py DIR

Create spec for a given Apache FUSEKI distribution directory, e.g.
"apache-jena-fuseki-3.9.0".
"""

from __future__ import print_function
import datetime
import os
import re
import sys


def main(args):
    if not args:
        print(__doc__, file=sys.stderr)
        sys.exit(1)

    if not re.match("apache-jena-fuseki-[0-9.]*", args[0]):
        print("DIR must be of the form apache-jena-fuseki-VERSION", file=sys.stderr)
        sys.exit(1)

    version = args[0].replace("apache-jena-fuseki-", "")

    buildroot = "$RPM_BUILD_ROOT/opt"

    print("""
Summary:    Inofficial bundle for FUSEKI triple store.
Name:       fusekibundle
Version:    %s
Release:    0
License:    Apache Version 2.0
ExclusiveArch:  x86_64
BuildRoot:  %%{_tmppath}/%%{name}-build
Group:      System/Base
Vendor:     Leipzig University Library, https://www.ub.uni-leipzig.de
URL:        https://github.com/miku/fusekibundle

%%description

Inofficial bundle for FUSEKI triple store. More information at: https://jena.apache.org

%%prep

%%build

%%pre
""" % version)

    dirs = [
        'bin',
        'webapp',
        'webapp/css',
        'webapp/images',
        'webapp/test',
        'webapp/fonts',
        'webapp/js',
        'webapp/js/app',
        'webapp/js/app/services',
        'webapp/js/app/controllers',
        'webapp/js/app/views',
        'webapp/js/app/models',
        'webapp/js/app/util',
        'webapp/js/app/templates',
        'webapp/js/lib',
        'webapp/js/lib/plugins',
        'webapp/js/lib/addon',
        'webapp/js/lib/addon/fold',
        'webapp/js/lib/lib',
        'webapp/js/lib/mode',
        'webapp/js/lib/mode/turtle',
        'webapp/js/lib/mode/javascript',
        'webapp/js/lib/mode/sparql',
        'webapp/js/lib/mode/xml',
        'webapp/WEB-INF',
    ]

    print('%%install')
    print()
    for dir in dirs:
        print('mkdir -p %s' % (os.path.join(buildroot, args[0], dir)))

    managed = []

    for root, dirs, files in os.walk(args[0]):
        for fn in files:
            path = os.path.join(root, fn)
            managed.append(os.path.join('/opt', path))

            if '/bin/' in path:
                print('install -m 755 %s %s' % (path, os.path.join(buildroot, path)))
            else:
                print('install -m 644 %s %s' % (path, os.path.join(buildroot, path)))

    print("""
%%post

%%clean

rm -rf $RPM_BUILD_ROOT
rm -rf %%{_tmppath}/%%{name}
rm -rf %%{_topdir}/BUILD/%%{name}

%%files
%%defattr(-,root,root)
""")

    for name in managed:
        print(name)


    print("""

%%postun

rm -rf /opt/apache-jena-fuseki-%s

%%changelog

* %s Martin Czygan
- autogenerated spec
    """ % (version, datetime.date.today().strftime("%a %b %d %Y")))


if __name__ == '__main__':
    main(sys.argv[1:])
