#!/usr/bin/env python
# coding: utf-8

"""USAGE: rpmutil.py DIR

Create an RPM spec[1] for a given Apache FUSEKI distribution directory (e.g.
apache-jena-fuseki-3.9.0) which can be obtained from
https://jena.apache.org/download/index.cgi.

This is run from Makefile, where you have to set the VERSION to match the
downloaded version.

[1] https://rpm-packaging-guide.github.io/

"""

from __future__ import print_function
import datetime
import os
import re
import sys


def main(args):
    if not args:
        print(__doc__, file=sys.stderr)
        sys.exit(1)

    if not re.match("apache-jena-fuseki-[0-9.]*", args[0]):
        print("DIR must be of the form apache-jena-fuseki-VERSION", file=sys.stderr)
        sys.exit(1)

    version = args[0].replace("apache-jena-fuseki-", "")

    buildroot = "$RPM_BUILD_ROOT/opt"

    print("""
Summary:    Inofficial bundle for FUSEKI triple store.
Name:       fusekibundle
Version:    %s
Release:    0
License:    Apache Version 2.0
ExclusiveArch:  x86_64
BuildRoot:  %%{_tmppath}/%%{name}-build
Group:      System/Base
Vendor:     Leipzig University Library, https://www.ub.uni-leipzig.de
URL:        https://github.com/miku/fusekibundle
Requires: java-1.8.0-openjdk
Requires(pre): /usr/sbin/useradd, /usr/bin/getent
Requires(postun): /usr/sbin/userdel

%%description

Inofficial bundle for FUSEKI triple store. More information at: https://jena.apache.org

%%prep

%%build

%%pre

/usr/bin/getent group fuseki > /dev/null || /usr/sbin/groupadd -r fuseki
/usr/bin/getent passwd fuseki > /dev/null || /usr/sbin/useradd -r -d /opt/fuseki -s /sbin/nologin -g fuseki fuseki

""" % (version))

    # find apache-jena-fuseki-3.9.0 -type d | cut -d '/' -f2- | tail +2
    dirs = [
        'bin',
        'webapp',
        'webapp/css',
        'webapp/images',
        'webapp/test',
        'webapp/fonts',
        'webapp/js',
        'webapp/js/app',
        'webapp/js/app/services',
        'webapp/js/app/controllers',
        'webapp/js/app/views',
        'webapp/js/app/models',
        'webapp/js/app/util',
        'webapp/js/app/templates',
        'webapp/js/lib',
        'webapp/js/lib/plugins',
        'webapp/js/lib/addon',
        'webapp/js/lib/addon/fold',
        'webapp/js/lib/lib',
        'webapp/js/lib/mode',
        'webapp/js/lib/mode/turtle',
        'webapp/js/lib/mode/javascript',
        'webapp/js/lib/mode/sparql',
        'webapp/js/lib/mode/xml',
        'webapp/WEB-INF',
    ]

    print('%%install')
    print()
    for dir in dirs:
        print('mkdir -p %s' % (os.path.join(buildroot, 'fuseki', dir)))

    print('mkdir -p $RPM_BUILD_ROOT/etc/systemd/system/')
    print('mkdir -p $RPM_BUILD_ROOT/etc/fuseki')

    managed = []
    binaries = ['fuseki-server', 'fuseki', 'fuseki-backup']

    for root, _, files in os.walk(args[0]):
        for fn in files:
            path = os.path.join(root, fn)
            path = path.replace("apache-jena-fuseki-%s" % version, "fuseki")

            managed.append(os.path.join('/opt', path))

            if fn == 'fuseki.service':
                print('install -m 644 fuseki/fuseki.service $RPM_BUILD_ROOT/etc/systemd/system/fuseki.service')

            if '/bin/' in path or fn in binaries:
                print('install -m 755 %s %s' % (path, os.path.join(buildroot, path)))
            else:
                print('install -m 644 %s %s' % (path, os.path.join(buildroot, path)))

    print("""
%%post

%%clean

rm -rf $RPM_BUILD_ROOT
rm -rf %%{_tmppath}/%%{name}
rm -rf %%{_topdir}/BUILD/%%{name}

%%files
%%defattr(-,fuseki,fuseki)
""")

    for name in managed:
        print(name)

    for dir in dirs:
        print('%%dir /opt/fuseki/%s' % (dir))

    print('%%dir /etc/fuseki')
    print('/etc/systemd/system/fuseki.service')
    print("""

%%postun

rm -rf /opt/fuseki
/usr/sbin/userdel fuseki

%%changelog

* %s Martin Czygan
- autogenerated spec
    """ % (datetime.date.today().strftime("%a %b %d %Y")))


if __name__ == '__main__':
    main(sys.argv[1:])
