#!/usr/bin/env python
# coding: utf-8

"""USAGE: rpmutil.py DIR

Create spec for a given Apache FUSEKI distribution directory, e.g.
"apache-jena-3.9.0".
"""

from __future__ import print_function
import datetime
import os
import re
import sys


def main(args):
    if not args:
        print(__doc__, file=sys.stderr)
        sys.exit(1)

    if not re.match("apache-jena-[0-9.]*", args[0]):
        print("DIR must be of the form apache-jena-VERSION", file=sys.stderr)
        sys.exit(1)

    version = args[0].replace("apache-jena-", "")

    buildroot = "$RPM_BUILD_ROOT/opt"

    print("""
Summary:    Inofficial bundle for FUSEKI triple store.
Name:       fusekibundle
Version:    %s
Release:    0
License:    Apache Version 2.0
ExclusiveArch:  x86_64
BuildRoot:  %%{_tmppath}/%%{name}-build
Group:      System/Base
Vendor:     Leipzig University Library, https://www.ub.uni-leipzig.de
URL:        https://github.com/miku/fusekibundle

%%description

Inofficial bundle for FUSEKI triple store. More information at: https://jena.apache.org

%%prep

%%build

%%pre
""" % version)

    dirs = [
        'bin',
        'src-examples',
        'src-examples/jena-examples',
        'src-examples/jena-examples/src',
        'src-examples/jena-examples/src/main',
        'src-examples/jena-examples/src/main/java',
        'src-examples/jena-examples/src/main/java/org',
        'src-examples/jena-examples/src/main/java/org/apache',
        'src-examples/jena-examples/src/main/java/org/apache/jena',
        'src-examples/jena-examples/src/main/java/org/apache/jena/example',
        'src-examples/jena-examples/src/main/java/org/apache/jena/example/helloworld',
        'src-examples/jena-examples/src/main/java/org/apache/jena/example/pizza',
        'src-examples/jena-examples/src/main/resources',
        'src-examples/jena-examples/src/main/resources/ontologies',
        'src-examples/jena-examples/src/main/resources/data',
        'src-examples/jena-examples/src/test',
        'src-examples/jena-examples/src/test/java',
        'src-examples/jena-examples/src/test/java/org',
        'src-examples/jena-examples/src/test/java/org/apache',
        'src-examples/jena-examples/src/test/java/org/apache/jena_examples',
        'src-examples/jena-examples/bin',
        'src-examples/arq',
        'src-examples/arq/examples',
        'src-examples/arq/examples/riot',
        'src-examples/arq/examples/engine',
        'src-examples/arq/examples/update',
        'src-examples/arq/examples/constructquads',
        'src-examples/arq/examples/bgpmatching',
        'src-examples/arq/examples/propertyfunction',
        'src-examples/arq/examples/filter',
        'src-examples/arq/examples/aggregates',
        'src-examples/data',
        'src-examples/jena',
        'src-examples/jena/examples',
        'src-examples/jena/examples/rdf',
        'src-examples/jena/examples/ontology',
        'src-examples/jena/examples/ontology/classHierarchy',
        'src-examples/jena/examples/ontology/describeClass',
        'src-examples/tdb',
        'src-examples/tdb/examples',
        'lib-src',
        'lib',
        'bat',
    ]

    print('%%install')
    print()
    for dir in dirs:
        print('mkdir -p %s' % (os.path.join(buildroot, args[0], dir)))

    managed = []

    for root, dirs, files in os.walk(args[0]):
        for fn in files:
            path = os.path.join(root, fn)
            managed.append(os.path.join('/opt', path))

            if '/bin/' in path:
                print('install -m 755 %s %s' % (path, os.path.join(buildroot, path)))
            else:
                print('install -m 644 %s %s' % (path, os.path.join(buildroot, path)))

    print("""
%%post

%%clean

rm -rf $RPM_BUILD_ROOT
rm -rf %%{_tmppath}/%%{name}
rm -rf %%{_topdir}/BUILD/%%{name}

%%files
%%defattr(-,root,root)
""")

    for name in managed:
        print(name)


    print("""

%%postun

rm -rf /opt/apache-jena-%s

%%changelog

* %s Martin Czygan
- autogenerated spec
    """ % (version, datetime.date.today().strftime("%a %b %d %Y")))


if __name__ == '__main__':
    main(sys.argv[1:])
